   executor: org.wso2.carbon.apimgt.sampleworkflow.BPMNApprovalExecutor
   property:
    - name: processDefinitionKey
      value: SampleApprovalWorkFlowProcess
    - name: username
      value: kermit
    - name: password
      value: kermit
    - name: clientId
      value: MLrrwN6WVs3SEUzJocTm_zj0HXga
    - name: clientSecret
      value: V1CEAmcQtWLuO8WbYr0yXpGfRCEa
    - name: tokenAPI
      value: https://localhost:9443/oauth2/token
    - name: callbackUrl
      value: https://localhost:9292/api/am/admin/v1.0/workflows
    - name: serviceEndpoint
      value: http://localhost:8080/activiti-rest/service

